### ISSUE TITLE
Failed to run in local

### ISSUE THREAD

**Issue by mendickxiao** [lukebond/microscanner-wrapper#15]
USE_LOCAL=1 MICROSCANNER_TOKEN=*** ./scan.sh bkimminich/juice-shop
which: no microscanner in (/sbin:/sbin:/bin:/usr/sbin:/usr/bin)
Sending build context to Docker daemon  2.095kB
Step 1/5 : FROM bkimminich/juice-shop
 ---> 343934d04e44
Step 2/5 : RUN if [ ! -d /etc/ssl/certs/ ] || { [ ! -f /etc/ssl/certs/ca-certificates.crt ] && [ ! -f /etc/ssl/certs/ca-bundle.crt ]; }; then   PACKAGE_MANAGER=$(basename     $({ command -v apk apt yum false 2>/dev/null || which apk apt yum false; }     | head -n1));   if [ "${PACKAGE_MANAGER}" = "apk" ]; then     apk --update add ca-certificates;   elif [ "${PACKAGE_MANAGER}" = "apt" ]; then     apt update       && apt install --no-install-recommends -y ca-certificates       && update-ca-certificates;   elif [ "${PACKAGE_MANAGER}" = "yum" ]; then     yum install -y ca-certificates;   else     echo 'ca-certificates not found and package manager not apk, apt, or yum. Aborting' >&2;     exit 1;   fi; fi;
 ---> Running in 32b797186633
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
Removing intermediate container 32b797186633
The command '/bin/sh -c if [ ! -d /etc/ssl/certs/ ] || { [ ! -f /etc/ssl/certs/ca-certificates.crt ] && [ ! -f /etc/ssl/certs/ca-bundle.crt ]; }; then   PACKAGE_MANAGER=$(basename     $({ command -v apk apt yum false 2>/dev/null || which apk apt yum false; }     | head -n1));   if [ "${PACKAGE_MANAGER}" = "apk" ]; then     apk --update add ca-certificates;   elif [ "${PACKAGE_MANAGER}" = "apt" ]; then     apt update       && apt install --no-install-recommends -y ca-certificates       && update-ca-certificates;   elif [ "${PACKAGE_MANAGER}" = "yum" ]; then     yum install -y ca-certificates;   else     echo 'ca-certificates not found and package manager not apk, apt, or yum. Aborting' >&2;     exit 1;   fi; fi;' returned a non-zero code: 99

**Comment by lukebond** [comment]
turns out it didn't support images that don't run as `root` and need the TLS certs :facepalm:
